name: Postgres Docker image with "baked-in" data
author: Snaplet, Inc.
description: Creates a Postgres Docker Image, with data from a Snaplet snapshot, for restoration in Codespaces, development environments.
inputs:
  docker-container-name:
    description: Name of docker database container
    required: false
  docker-image-tag:
    description: Name of docker image
    required: true
  snaplet-database-url:
    description: Connection string to restore a snapshot
    required: true
    type: string
  snaplet-restore-command:
    description: Command used to restore a snapshot
    required: false
    type: string
    default: snaplet snapshot restore --latest
runs:
  using: "composite"
  steps:
    - name: Install Snaplet
      run: |
        curl -sS "https://app.snaplet.dev/get-cli/" | bash &> "/dev/null"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Restore snapshot
      run: ${{ inputs.snaplet-restore-command }}
      shell: bash
      env:
        SNAPLET_TARGET_DATABASE_URL: ${{ inputs.snaplet-database-url }}

    - name: Commit and push Docker image
      run: |
        CONTAINER_PORT=$(echo "${{ inputs.snaplet-database-url }}" | sed 's/.*:\([0-9]*\)\/.*/\1/;s/^$/5432/')
        CONTAINER_ID=$(docker ps -f publish=$CONTAINER_PORT --format {{.ID}})
        CONTAINER_NAME=${{ inputs.docker-container-name }}
        CONTAINER=${DOCKER_CONTAINER_NAME:-$CONTAINER_ID}
        docker commit $CONTAINER ${{ inputs.docker-container-tag }}
        docker push ${{ inputs.docker-container-tag }}
      shell: bash
