name: Snaplet Restore
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # 5 AM everyday

jobs:
  # Label of the runner job
  snaplet-restore:
    name: Snaplet Restore
    timeout-minutes: 10
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest # Must match the database where snapshot was taken
        env:
          PGDATA: /data # Important: data location has to be changed as default is defined as a volume, so snapshot won't persist
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: snapshot
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name snapshot
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GHCR_CONTAINER_REGISTRY_SERVER }}
          username: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.GHCR_CONTAINER_REGISTRY_PASSWORD }}

      - name: Snaplet Restore
        uses: ./
        with:
          docker-image-tag: ghcr.io/snaplet/publish-postgres-with-data-docker-action_database
        env:
          SNAPLET_ACCESS_TOKEN: ${{ secrets.SNAPLET_ACCESS_TOKEN }}
          SNAPLET_PROJECT_ID: ${{ secrets.SNAPLET_PROJECT_ID }}
          SNAPLET_TARGET_DATABASE_URL: postgres://postgres:postgres@localhost:5432/snapshot
          